logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: TRACE

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true